"""Add sensors and link measurements to sensors

Revision ID: 182a516f398e
Revises: ed93a3719bb7
Create Date: 2026-08-29 19:52:01.130560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182a516f398e'
down_revision: Union[str, Sequence[str], None] = 'ed93a3719bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_uid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_sensor_uid'), 'sensors', ['sensor_uid'], unique=True)
    op.add_column('measurements', sa.Column('sensor_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('measurements_device_id_fkey'), 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'sensors', ['sensor_id'], ['id'])
    op.drop_column('measurements', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key(op.f('measurements_device_id_fkey'), 'measurements', 'devices', ['device_id'], ['id'])
    op.drop_column('measurements', 'sensor_id')
    op.drop_index(op.f('ix_sensors_sensor_uid'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
