"""Replace sensor readings with measurements

Revision ID: ed93a3719bb7
Revises: 5c8d7ad4e5b9
Create Date: 2026-08-29 16:29:45.826389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed93a3719bb7'
down_revision: Union[str, Sequence[str], None] = '5c8d7ad4e5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Create measurements table
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    connection = op.get_bind()

    # Create missing devices from old sensor readings
    connection.execute(
        sa.text("""
            INSERT INTO devices (
                device_uid,
                name,
                location,
                created_at
            )
            SELECT DISTINCT
                device_id,
                'Migrated Device',
                'Unknown',
                NOW()
            FROM sensor_readings
            WHERE device_id NOT IN (
                SELECT device_uid FROM devices
            )
        """)
    )

    # Migrate temperature measurements
    connection.execute(
        sa.text("""
            INSERT INTO measurements (
                device_id,
                metric,
                value,
                unit,
                created_at
            )
            SELECT
                devices.id,
                'temperature',
                sensor_readings.temperature,
                'celsius',
                sensor_readings.created_at
            FROM sensor_readings
            JOIN devices
                ON devices.device_uid = sensor_readings.device_id
        """)
    )

    # Migrate humidity measurements
    connection.execute(
        sa.text("""
            INSERT INTO measurements (
                device_id,
                metric,
                value,
                unit,
                created_at
            )
            SELECT
                devices.id,
                'humidity',
                sensor_readings.humidity,
                'percent',
                sensor_readings.created_at
            FROM sensor_readings
            JOIN devices
                ON devices.device_uid = sensor_readings.device_id
        """)
    )

    # Remove old table
    op.drop_table("sensor_readings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_readings_pkey'))
    )
    op.drop_table('measurements')
    # ### end Alembic commands ###
